### ISSUE TITLE
[Feature] Seperate commiting user from user displayed

### ISSUE THREAD

**Issue by cyacedev** [lowlighter/metrics#1]
## description
I would really enjoy the ability to separately specify the bot account/token that commits the newly generated svg and the account/token from which the data is collected.

## background
Currently I have the problem that I would like to collect data from all my repositories (therefore I need my personal token) and I don't wan't to commit the generated image with my personal token due to it generating fake stats.

**Comment by lowlighter** [comment]
I'll look into splitting the token that gathers data and the one that commits stats, it's a good idea

**Comment by lowlighter** [comment]
[Release 1.2](https://github.com/lowlighter/metrics/releases/tag/v1.2) now supports the `committer_token` option, so you can use a personal token for `token` and a bot token for `committer_token` to avoid polluting your commits history on you main account 👍

Thanks for your suggestion !

**Comment by cyacedev** [comment]
Thanks for the quick response, it works perfectly!
