### ISSUE TITLE
feat(plugins/calendar): add new "history" option to display previous years

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#1002]
(title)

**Comment by ljharb** [comment]
Thank you! I've enabled the calendar plugin on my profile; works great!

(2021 shows some gaps that aren't really there, but github's api flakes on that sometimes, so presumably they'll fill in on future runs)

**Comment by ljharb** [comment]
although now it shows "0 languages", not sure if that's related

**Comment by lowlighter** [comment]
> although now it shows "0 languages", not sure if that's related

I think it's a separate issue, all plugins are independant by design (except for the base/core ones)

But I'm not sure what's the error, it seems to be fine when I tried to reproduce, and it seems to be fine on your [current render](https://github.com/ljharb/ljharb/blob/f8774633f7e2ef34beaf90a9d3cca23e6fbe23c1/github-metrics.svg)

**Comment by ljharb** [comment]
that's not the current render; https://github.com/ljharb/ljharb/blob/f53e15ee9c4e70141b4b64e6779518efd076492d/github-metrics.svg is, and the one i was talking about is https://github.com/ljharb/ljharb/commit/fcf04d6b4756b85ff62ae8dcb35464cbfb1eb329

**Comment by lowlighter** [comment]
Ah yes indeed, though from what I see the [latest run](https://github.com/ljharb/ljharb/runs/6201755940?check_suite_focus=true#step:2:774) seems to be [correct](https://raw.githubusercontent.com/ljharb/ljharb/9afbf7d79048c23732d2f584ccc5fe128a1a25ae/github-metrics.svg).

It may be possible that the rate-limit is reached during the initial fetching of repositories and the error is improperly caught resulting in empty results. Will try to investigate on it 👍 

____

I noticed you're using `columns` display, but there's currently an unfixable issue (#839) for it, so it's better to switch to either `large` or `regular` to avoid render issues

**Comment by ljharb** [comment]
hmm, that's unfortunate - couldn't i just configure explicitly which thing goes in which columns?

**Comment by lowlighter** [comment]
> hmm, that's unfortunate - couldn't i just configure explicitly which thing goes in which columns?

Yes, that's actually what I do with my own profile
Basically I just use differents jobs to use generate multiple outputs, and I use the `align` attribute which kinds act like "float" in Github flavored markdown

```html
<img align="left" width="390" alt="🦑" src="https://gist.githubusercontent.com/lowlighter/3c6eaedf50273adfb7a510822672f570/raw/sponsors.svg">
<img align="right" width="390" alt="🦑" src="https://gist.githubusercontent.com/lowlighter/3c6eaedf50273adfb7a510822672f570/raw/achievements.svg">
```

As a bonus, it should renders nice on mobile since it'll act as a "line-break" if screen is smaller

The issue with current `columns` issue is that although theorically `@media-queries` are allowed and functional in `<svg>` elements, they're ignored when a svg is embed through `<img src>` tag

**Comment by ljharb** [comment]
right - what i'd prefer tho is to configure it so it generates a single, multi-column SVG where no automatic breaks are needed because i've hardcoded which plugins appear in which column :-)
