### ISSUE TITLE
Nightscout Plugin

### ISSUE THREAD

**Issue by legoandmars** [lowlighter/metrics#102]
[Nightscout](https://github.com/nightscout/cgm-remote-monitor) is an open source website that people in the diabetes community use to easily keep track of Continuous Glucose Monitor glucose data in the cloud

I've already made a plugin on my fork to integrate this for my own personal use, and I'd be happy to PR it in, however:
* It's relatively niche
* Unsure how much this aligns with the direction you want to go in with this project

Let me know if this is something you'd be interested in. Here's [my fork](https://github.com/legoandmars/metrics) and a preview:
![Nightscout Metrics](https://raw.githubusercontent.com/legoandmars/legoandmars/master/metrics.plugin.nightscout.svg)

**Comment by lowlighter** [comment]
Hello!

I'll be happy to merge it 🙂 
At first metrics was more targetted for GitHub stuff, but now I guess any dynamic data related to yourself you'd like to share is fine. Plus SVGs can actually be embed everywhere like your personal website so it's ok to not have only dev-related stuff 👍

As I'm not diabetic myself too, will it be ok to keep your example on the main repo?  I would understand too if you'd like your Glucose rate not being shipped with each release

Ps: I hope it was not too difficult to setup a new plugin

**Comment by legoandmars** [comment]
I'm fine with keeping my example on the main repo, I intend to keep it up and running for a while. I'll PR shortly.
