### ISSUE TITLE
Stackoverflow stats

### ISSUE THREAD

**Issue by mehdibo** [lowlighter/metrics#105]
Show stackoverflow stats like:
 - Reputation points
 - Number of Questions and Answers
 - Top voted answer
 - Badges

**Comment by lowlighter** [comment]
That's a good idea!

**Comment by lowlighter** [comment]
[Stackoverflow plugin](https://github.com/lowlighter/metrics/blob/master/source/plugins/stackoverflow/README.md) is now available on `@master` branch, and will be available on `@latest` in a few weeks 🙂
