### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ardittristan** [lowlighter/metrics#11]
**Bug description**
Invalid SSL certificate

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/42787508/101362981-18174380-38a1-11eb-863d-bf7647d3af89.png)

**Comment by lowlighter** [comment]
Hi, thanks for notifying me !

It should be solved now 👍 
I made some changes with certificates earlier and didn't notice it broke stuff.
