### ISSUE TITLE
Support emojis

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#116]
Hey, countless things can't support emojis currently, for example commit messages. Using something like twemoji-parser would allow us to add emoji support. It'd be really cool.

**Comment by lowlighter** [comment]
Emojis should already be supported in mosft (if not all) plugins:

For example, activity or tweets plugin:
![](https://user-images.githubusercontent.com/22963968/107223307-52729d80-6a16-11eb-9eeb-c70f806e1342.png)
![](https://user-images.githubusercontent.com/22963968/107223433-7d5cf180-6a16-11eb-8395-56e5e53a009b.png)

I don't have in mind all plugins list, but I'm pretty sure it also works with other plugins like the recently starred one too.

Do you have any examples on where emojis don't work?

**Comment by Milo123459** [comment]
In commit messages it doesn't work. Using twemoji will also give a cleaner look

**Comment by lowlighter** [comment]
For commit messages, it may be either be a GitHub limitation or maybe these are stored somewhere else (metrics doesn't do any additional processing on these, so it isn't the one stripping out emojis). I'll check when I'll implement activity plugin for repository template.
  
As for twemoji I'll take a look at it to check what's the best way of integrating it 👍

**Comment by Milo123459** [comment]
[twemoji-parser](https://npmjs.com/package/twemoji-parser) is pretty good.

**Comment by lowlighter** [comment]
Twemoji support will arrive with #121 👍
As for commits comments, they seems already supported natively (see illustrations in PR above)

As you said twemoji-parser is pretty good, a bit sad that they aren't any built-in replacer though 🙂
