### ISSUE TITLE
Language stats broken?

### ISSUE THREAD

**Issue by b3z** [lowlighter/metrics#120]
![image](https://user-images.githubusercontent.com/47346598/107475326-35ec7780-6b74-11eb-9c1a-3a70dd736d8c.png)
These are my stats. But if you look at my repositories I wonder how this can be? Isn't it way too much haskell?

See https://github.com/b3z for repos. (Only 12 repos so easy to approximate by hand)

**Comment by lowlighter** [comment]
Not sure too, but using a scopeless token seems to yield correct results:

![Metrics](https://metrics.lecoq.io/b3z?template=classic&base.activity=0&base.community=0&base.repositories=0&base.metadata=0&languages=1&languages.colors=github&languages.details=bytes-size%2C%20percentage&languages.threshold=0%25&config.timezone=Europe%2FParis&config.animated=true)

It may be related to #59 and https://github.com/lowlighter/metrics/issues/115#issuecomment-775392173, basically filter used to select repositories was changed to nothing (previously it was only processing repositories you owned) but now it includes repositories you own, contributed to and from organizations you're a member (whether you worked in them or not)

It could also be that you have large private repositories skewing resulting metrics (languages stats are actually computed through total bytes size from each language recorded). You can skip repositories with `plugin_languages_skipped` if needed.

You can pass `plugin_languages_details: bytes-size, percentage` for more detailed output (like above) so it might help troubleshoot. 

Finally, `debug: yes` will log which repositories were used and additional informations. 
If you find something odd in them, I'll take a lookt at it 👍
