### ISSUE TITLE
PageSpeed plugin causing errors in workflow runs.

### ISSUE THREAD

**Issue by mrBackSlash-it** [lowlighter/metrics#14]
**Bug description**
With the new metrics version (v2.25) my github workflow fails.

**Expected behavior**
The workflow should run normally but with the 'latest' tag set in the workflow file, now my workflow fails.

**To Reproduce**
I think the plugin affected is PageSpeed, because the error is related to that.
I fixed by setting the tag to v2.24 in the workflow file.

**Additional context and screenshots**

This is the error message:
```
ejs:412 410| <div class="row fill-width"> 411| <section class="categories"> >> 412| <% for (const {score, title} of computed.plugins.pagespeed.scores) { %> 413| <div class="categorie column"> 414| <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" width="50" height="50" class="gauge <%= !Number.isNaN(score) ? (score >= 0.9 ? 'high' : score >= 0.5 ? 'average' : 'low') : '' %>"> 415| <circle class="gauge-base" r="53" cx="60" cy="60"></circle> computed.plugins.pagespeed.scores is not iterable
```

![fail](https://user-images.githubusercontent.com/58268988/101644493-8856ce00-3a35-11eb-978b-e138358d5cf3.png)

**Comment by lowlighter** [comment]
Hi,
Thanks for the feedback.

I made some changes to the PageSpeed plugin in the new version [v2.6](https://github.com/lowlighter/metrics/releases/tag/v2.6) and it should be fixed now. If it still doesn't work, try enabling the `debug` option, I'll try to investigate more 👍

**Comment by mrBackSlash-it** [comment]
Issue is now resolved for me, it's working fine. Thanks a lot for the help! 😄

**Comment by joe733** [comment]
This issue has resurfaced 😕 https://github.com/joe733/joe733/actions/runs/445593935

**Comment by lowlighter** [comment]
Hello !

Seems I haven't added enough logs to debug it yet. 

I'm wondering if it isn't an uncaught error related to the rate-limit/captcha of the pagespeed api since it seems you don't have a token, and your runs are passing from time to time.

Anyway, I'll add more logs in next release to get more clues.

Thanks for your feedback, and happy holidays !

**Comment by joe733** [comment]
Hi, Thanks for the taking note.

> I'm wondering if it isn't an uncaught error related to the rate-limit/captcha of the pagespeed api since it seems you don't have a token, and your runs are passing from time to time.

Have you tried reducing the cron job frequency to say something like: `'0 0 * * *'` (every 12 AM UTC)? If not I'll try. I guess it might solve the issue regarding the rate-limit.

And happy holidays to you too!

**Comment by lowlighter** [comment]
@joe733 
`0 0 * * *` is actually the schedule I use in my personal [workflow](https://github.com/lowlighter/lowlighter/blob/master/.github/workflows/metrics.yml#L4) and it seems fine.

But I think I've figured out the issue, errors of `pagespeed` plugin were indeed badly caught. 
It should now fails "gracefully" with additional logs in the runner. 
<img src="https://user-images.githubusercontent.com/22963968/103181571-bdbb4280-48a2-11eb-9a07-b08c6eb9ddb6.png" width="400">

Don't hesitate to ping me if you still have this issue, I'll look at it and will hopefully be able to solve it next time.

Thanks a lot !

**Comment by joe733** [comment]
Thanks a lot for the changes you made in #28. For now it looks good! Will inform when I see something. You can close the issue. 🙂

**Comment by lowlighter** [comment]
Thanks !
