### ISSUE TITLE
Achievements metrics shows (Unexpected Error)

### ISSUE THREAD

**Issue by orsnaro** [lowlighter/metrics#1479]
### Discussed in https://github.com/lowlighter/metrics/discussions/1478

<div type='discussions-op-text'>

<sup>Originally posted by **orsnaro** July 11, 2023</sup>
![image](https://github.com/lowlighter/metrics/assets/77698890/83ac4ad0-97a0-4b77-9ea8-b2ae3f034352)

[metrics code in my `metrics_action.yml`](https://github.com/orsnaro/orsnaro/blob/main/.github/workflows/metrics_action.yml#L73C11-L73C11)</div>

**Comment by LuanRoger** [comment]
Same here. 
The log does not help so much, it's just this that shows up:
```
...
  metrics/compute/plugins > achievements > setup found (?)
  metrics/compute/plugins > achievements > setup found (?)
  metrics/compute/plugins > achievements > setup found (?)
...
```
> Usign the `debug: yes` flag.

This was thrown soo many times, probably because the auto-retry. I cancel the action execution after 7 min.

**Comment by redlinejoes** [comment]
I also see the issue: "Unexpected error"
I see this in the achievements workflow
```yaml
  [
    {
      name: 'achievements',
      result: {
        error: {
          message: 'Unexpected error',
          instance: 'Failed to initiate total for achievement plugin'
        }
      }
    }
  ]
```

**Comment by TonyCrane** [comment]
GitHub have added a home page to GitHub Search, so metrics can't get total repository/user/issue number from https://github.com/search.

And the query string can't be empty, so maybe we can try searching `created:>2007`, although this may be not exact, but at least it works.

```mjs
      for (let i = 0; (i < 100) && ((!total.users) || (!total.repositories)); i++) {
        const page = await browser.newPage()
        await page.goto("https://github.com/search?q=+created%3A%3E2007")
        const totalres = await page.evaluate(() => [...[...document.querySelectorAll("h2")].filter(node => /Filter by/.test(node.innerText)).shift()?.nextSibling?.innerText.trim().matchAll(/(?<type>Repositories|Users|Issues)\n(?<count>.*?)M/g) ?? []]) ?? null
        for (const result of totalres) {
          const type = result[1]?.toLowerCase()
          console.debug(`metrics/compute/plugins > achievements > setup found ${type ?? "(?)"}`)
          const count = result[2] ?? ""
          if ((count !== "") && (!total[type])) {
            total[type] = Number(count) * 10e5
            console.debug(`metrics/compute/plugins > achievements > set total.${type} to ${total[type]}`)
          }
        }
        await page.close()
        await imports.wait(10 * Math.random())
      }
```

**Comment by X-itachi-X** [comment]
> GitHub have added a home page to GitHub Search, so metrics can't get total repository/user/issue number from https://github.com/search.
> 
> And the query string can't be empty, so maybe we can try searching `created:>2007`, although this may be not exact, but at least it works.
> 
> ```js
>       for (let i = 0; (i < 100) && ((!total.users) || (!total.repositories)); i++) {
>         const page = await browser.newPage()
>         await page.goto("https://github.com/search?q=+created%3A%3E2007")
>         const totalres = await page.evaluate(() => [...[...document.querySelectorAll("h2")].filter(node => /Filter by/.test(node.innerText)).shift()?.nextSibling?.innerText.trim().matchAll(/(?<type>Repositories|Users|Issues)\n(?<count>.*?)M/g) ?? []]) ?? null
>         for (const result of totalres) {
>           const type = result[1]?.toLowerCase()
>           console.debug(`metrics/compute/plugins > achievements > setup found ${type ?? "(?)"}`)
>           const count = result[2] ?? ""
>           if ((count !== "") && (!total[type])) {
>             total[type] = Number(count) * 10e5
>             console.debug(`metrics/compute/plugins > achievements > set total.${type} to ${total[type]}`)
>           }
>         }
>         await page.close()
>         await imports.wait(10 * Math.random())
>       }
> ```

can you explain please what I have to do to make it work?

**Comment by JohnyP36** [comment]
I have the same problem and disabling the workflow and then enabling it again does not work.

**Comment by redlinejoes** [comment]
> 

Your question has been answered already, but you have to read the full contents of the issue. I will copy the direct link to make it easier for you to read. 

https://github.com/lowlighter/metrics/issues/1479#issuecomment-1633615855

**Comment by JohnyP36** [comment]
> > 
> 
> Your question has been answered already, but you have to read the full contents of the issue. I will copy the direct link to make it easier for you to read.
> 
> [#1479 (comment)](https://github.com/lowlighter/metrics/issues/1479#issuecomment-1633615855)

Thanks. But this means the problem is not on my side but with metrics? If yes, thank you for the fix in advance.

**Comment by redlinejoes** [comment]
> > > GitHub have added a home page to GitHub Search, so metrics can't get total repository/user/issue number from https://github.com/search.
> > > And the query string can't be empty, so maybe we can try searching `created:>2007`, although this may be not exact, but at least it works.
> > > ```js
> > >       for (let i = 0; (i < 100) && ((!total.users) || (!total.repositories)); i++) {
> > >         const page = await browser.newPage()
> > >         await page.goto("https://github.com/search?q=+created%3A%3E2007")
> > >         const totalres = await page.evaluate(() => [...[...document.querySelectorAll("h2")].filter(node => /Filter by/.test(node.innerText)).shift()?.nextSibling?.innerText.trim().matchAll(/(?<type>Repositories|Users|Issues)\n(?<count>.*?)M/g) ?? []]) ?? null
> > >         for (const result of totalres) {
> > >           const type = result[1]?.toLowerCase()
> > >           console.debug(`metrics/compute/plugins > achievements > setup found ${type ?? "(?)"}`)
> > >           const count = result[2] ?? ""
> > >           if ((count !== "") && (!total[type])) {
> > >             total[type] = Number(count) * 10e5
> > >             console.debug(`metrics/compute/plugins > achievements > set total.${type} to ${total[type]}`)
> > >           }
> > >         }
> > >         await page.close()
> > >         await imports.wait(10 * Math.random())
> > >       }
> > > ```
> > 
> > 
> > can you explain please what I have to do to make it work?
> 
> @X-itachi-X probably says to edit the http here [`index.mjs : line 85`](https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/index.mjs#L85C1-L86C1)

It is more than line#85.
I tried just to replace line$85, and it failed because you need to replace all the different code and then it will work. 
See my new profile page, for example https://github.com/redlinejoes

**Comment by redlinejoes** [comment]
> GitHub have added a home page to GitHub Search, so metrics can't get total repository/user/issue number from https://github.com/search.
> 
> And the query string can't be empty, so maybe we can try searching `created:>2007`, although this may be not exact, but at least it works.
> 
> ```js
>       for (let i = 0; (i < 100) && ((!total.users) || (!total.repositories)); i++) {
>         const page = await browser.newPage()
>         await page.goto("https://github.com/search?q=+created%3A%3E2007")
>         const totalres = await page.evaluate(() => [...[...document.querySelectorAll("h2")].filter(node => /Filter by/.test(node.innerText)).shift()?.nextSibling?.innerText.trim().matchAll(/(?<type>Repositories|Users|Issues)\n(?<count>.*?)M/g) ?? []]) ?? null
>         for (const result of totalres) {
>           const type = result[1]?.toLowerCase()
>           console.debug(`metrics/compute/plugins > achievements > setup found ${type ?? "(?)"}`)
>           const count = result[2] ?? ""
>           if ((count !== "") && (!total[type])) {
>             total[type] = Number(count) * 10e5
>             console.debug(`metrics/compute/plugins > achievements > set total.${type} to ${total[type]}`)
>           }
>         }
>         await page.close()
>         await imports.wait(10 * Math.random())
>       }
> ```

I have tested and implemented your code, and it works as expected. Thank you for your contribution!

**Comment by obfuscatedgenerated** [comment]
I'm fairly certain this bug is causing Actions builds to hang for 10 minutes or more looking at the timing of this issue and my logs (click to view on the web):
[![logs showing long builds since a little over 3 weeks ago](https://github.com/lowlighter/metrics/assets/75035364/e0f4231c-937d-470a-9cba-08301c9849b6)](https://github.com/obfuscatedgenerated/obfuscatedgenerated/actions?page=2)

It's probably a good idea to get the fix into a published GitHub release as soon as possible so it doesn't burn through everyone's actions minutes (since most use `lowlighter/metrics@latest` as advised in the setup)

**Comment by redlinejoes** [comment]
> I'm fairly certain this bug is causing Actions builds to hang for 10 minutes or more looking at the timing of this issue and my logs:
> ![logs showing long builds since a little over 3 weeks ago](https://github.com/lowlighter/metrics/assets/75035364/e0f4231c-937d-470a-9cba-08301c9849b6)
> 
> It's probably a good idea to get the fix into a published GitHub release as soon as possible so it doesn't burn through everyone's actions minutes (since most use `lowlighter/metrics@latest` as advised in the setup)
> 

My actions jumped to over 11 minutes because of this issue. If you implement the changes outlined in this thread it will run faster again. Make sure to change the year to capture pre-2007 content if you have any. That is referenced in this thread too.

**Comment by AjaniBilby** [comment]
This issue is closed and it looks like a PR has been merged solving this issue...
But I'm still getting it 🤔

**Comment by RSickenberg** [comment]
Still the issue with the latest version.

<img width="784" alt="image" src="https://github.com/lowlighter/metrics/assets/16922548/82d3cf98-b561-4ef9-a37e-3343505487a5">
