### ISSUE TITLE
Quality of skyline is pretty bad

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#154]
![image](https://salvage.is-a-legend.xyz/⁠‍⁠‌‌​‍⁠⁠‌‌‌​‍‍‌​⁠⁠​‌‌‍‍‍​) as you can see, it does look kinda bad. is there a way to increase the quality?

**Comment by lowlighter** [comment]
I'll add an option to be able to configure it (these are scaled down to 0.5 to save space)
But as base64 encoded gif don't work in GitHub flavored SVG, you still won't be able to set quality to 1 with a lot of frames (it'll probably won't load or render)

**Comment by Milo123459** [comment]
Ah

**Comment by lowlighter** [comment]
Added `plugin_skyline_quality` in b064ed1 (like said before if you set it to 1, don't set plugin_skyline_frames` too high)

<img src="https://raw.githubusercontent.com/lowlighter/lowlighter/master/metrics.plugin.skyline.svg" width="400">
