### ISSUE TITLE
Scaling issue (to big 😅)

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#155]
![image](https://free-robux.fun/​‍⁠​​​​​‍‌‌‌‍‍​⁠⁠​​‌​‍​​‍​) you can probably see it's way to big. i haven't configured padding but yea, this is very low on priority lol

**Comment by lowlighter** [comment]
Probably was too generous with default padding, though it doesn't seem too bad for now but I'll remove 1-2%

**Comment by Milo123459** [comment]
All right! Mind checking out my discussion I made?
