### ISSUE TITLE
Twemoji doesn't work with github emojis (ie: :electron:)

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#157]
Twemoji can't render things like :electron: or :octocat: because they aren't built into twemoji, I had a look at the code and wasn't sure how I'd go about fixing it.

**Comment by lowlighter** [comment]
I'll check, but it's probably not a twemoji issue, I think it's better that these render even when twemoji option is disabled (or maybe through a separate option)

I'll experiment a bit to check how many GitHub custom emojis exists, and it it's easy to integrate them in end result 👍🏼

**Comment by lowlighter** [comment]
Added in #158
