### ISSUE TITLE
Add hashnode as post external source in recent post plugin

### ISSUE THREAD

**Issue by luisfalconmx** [lowlighter/metrics#162]
## Request
I would like [hashnode](https://hashnode.com/) to be added as external source of posts in Recent posts plugin.

![scrnli_3_1_2021_9-23-32 AM](https://user-images.githubusercontent.com/57654255/109518400-d3e6aa00-7a6f-11eb-9af3-1224e75f6ba1.png)

## What is hashnode?
Like dev.to, it is a blogging platform for developers where you can open your own blog with your own domain for free in a matter of minutes.

![scrnli_3_1_2021_9-30-00 AM](https://user-images.githubusercontent.com/57654255/109519285-b6661000-7a70-11eb-8d9f-7f9e4fe2b7ec.png)

## Github Actions Reference
Find on the github marketplace an action called [Hashnode Blog](https://github.com/marketplace/actions/hashnode-blog) that pulls the most recent posts from a hashnode account and inserts them into the Readme file.

![scrnli_3_1_2021_9-34-56 AM](https://user-images.githubusercontent.com/57654255/109520063-705d7c00-7a71-11eb-9e4f-e776fe2a44b2.png)

It may be useful to review the code for that project to see how to extract the data.

**Comment by lowlighter** [comment]
Will look into it 👍🏼

**Comment by lowlighter** [comment]
This is now available on `@master` branch and will be available on `@latest` on next release
