### ISSUE TITLE
Private data is not included

### ISSUE THREAD

**Issue by DeeshanSharma** [lowlighter/metrics#17]
**Bug description**
I used the repo permission in my token and passed it to the yml in the repo but the private data is not being included in the metrics. But it is showing in the metadata that this includes private data. And maybe it's not a bug and I might have done something wrong.

**Expected behavior**
The expected behavior was it should count my private repos and also my private commits.

**To Reproduce**
To reproduce just pass the token with repo permission in the secrets of the repo and then pass it in the yml file.

**Additional context and screenshots**
The rest of the things are working great and are awesome.

Really appreciate your work

**Comment by lowlighter** [comment]
Hi, thanks for reaching out !

Can you check that `Include private contribution on my profile` is enabled in your account settings ?

![image](https://user-images.githubusercontent.com/22963968/101982292-1ff53000-3c73-11eb-86ec-e48a8ba6dfc6.png)

If it didn't, try relaunching the workflow after enabling it (image may not refresh instantly so you may need to wait a bit)

I don't use the full `repo` scope myself so it's entirely possible it's a bug. 
I'll try to investigate more if the above didn't solve your problem 👍

Have a nice day !

**Comment by DeeshanSharma** [comment]
Thanks for replying,

This option is already enabled as I am using some more similar things on my profile readme and they are working correctly.

Good Day

**Comment by lowlighter** [comment]
I'll look into it 👍

**Comment by DeeshanSharma** [comment]
Ok sure

**Comment by lowlighter** [comment]
So I tested it a few minutes ago, and could not reproduce 😕

Below is the troubleshooting I made : 

I ran my workflow twice to test, once with a full `repo` scope token, and then again with the token without scopes and here are the results :

<table>
  <tr>
    <th>token with no scopes</th>
    <th>token repo scope</th>
  </tr>
  <tr>
    <td><img width="350" src="https://raw.githubusercontent.com/lowlighter/lowlighter/2f44154188a5a267d6dd413c137df556ebedd804/metrics.svg"></td>
    <td><img width="350" src="https://raw.githubusercontent.com/lowlighter/lowlighter/4230e9157d708a2ae8db3ef7e9c03f1c3843c63a/metrics.svg"></td>
  </tr>
</table>

From what I see, it seems to be coherent with my current public/private metrics so it seems ok.

So I investigated from your profile readme, and both [lowlighter/metrics](https://github.com/lowlighter/metrics) and [anuraghazra/github-readme-stats](https://github.com/anuraghazra/github-readme-stats) stats seems to match : 

<table>
  <tr>
    <th>token with no scopes</th>
    <th>token repo scope</th>
  </tr>
  <tr>
    <td><img width="350" src="https://camo.githubusercontent.com/4eacb3c40be549315ab142438d7c1d675faafccdea2c251b332d1f3f64e04a29/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d4465657368616e536861726d612673686f775f69636f6e733d7472756526636f756e745f707269766174653d74727565267468656d653d746f6b796f6e696768742662675f636f6c6f723d6666666666663030"><br><img width="350" src="https://camo.githubusercontent.com/fe5ff691ef4dd7d44f4cbc4349f2933c19f4027098e5c39aa2ebc3b38a175ec1/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f746f702d6c616e67732f3f757365726e616d653d4465657368616e536861726d61266c61796f75743d636f6d70616374267468656d653d746f6b796f6e696768742662675f636f6c6f723d6666666666663030"></td>
    <td><img width="350" src="https://raw.githubusercontent.com/DeeshanSharma/DeeshanSharma/228c5b0a26a5afbd40fc337915cb9169495ce3f9/github-metrics.svg"></td>
  </tr>
</table>

I noticed indeed that your [DenverCoder1/github-readme-streak-stats](https://github.com/DenverCoder1/github-readme-streak-stats) contributions is slightly different from what seems to be expected, but from their [readme](https://github.com/DenverCoder1/github-readme-streak-stats#how-these-stats-are-calculated) : 

> Contributions include commits, pull requests, and issues that you create in standalone repositories 

So by summing up all your metrics from the `Activity` section of [lowlighter/metrics](https://github.com/lowlighter/metrics) : `128+3+2+2+3 = 138 ≃ 140` : 

<img width="350" src="https://camo.githubusercontent.com/be74e049774a0a27e4747815b148b5f56664547245568cfc88e4f4280d810515/68747470733a2f2f6769746875622d726561646d652d73747265616b2d73746174732e6865726f6b756170702e636f6d2f3f757365723d6465657368616e736861726d61267468656d653d6461726b">

There's a difference of 2 contributions somewhere but I don't think it's really revelant, probably a metric which is not tracked. 
So I guess that all three plugins seems to be correctly working.

Let me know if I have missed something 🙂

**Comment by DeeshanSharma** [comment]
Hey,

Thanks, actually I really forgot about that, my bad, it's working correctly awesome job buddy really appreciate that.

Good Luck

**Comment by lowlighter** [comment]
No problems ! 
Glad you appreciate it 🙂
