### ISSUE TITLE
Add option to turn uglify off

### ISSUE THREAD

**Issue by SuperSandro2000** [lowlighter/metrics#170]
I updated to the latest version and got hit with the following diff https://github.com/SuperSandro2000/SuperSandro2000/commit/7c32e8ccaface0d41ef11cf8d0a22ab8d3164383. It would be great to add an option to not minify/uglify the svg.

**Comment by lowlighter** [comment]
You can turn if off by setting `optimize: no`.

https://github.com/lowlighter/metrics/blob/56e3ff6ae15cc90c7f5d61ee43efcdd8558add5c/source/plugins/core/metadata.yml#L54-L59

It was actually the default behaviour from prior versions, but at some point this option stopped working
