### ISSUE TITLE
When using twemoji, spaces around the emojis are removed

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#171]
![img](https://salvage.is-inside.me/e9wboBYS.png)

**Comment by lowlighter** [comment]
This is caused by #172 which seems to break even more stuff than whitespace.
Closing this as whitespaces should correctly render with optimize option disabled

**Comment by Milo123459** [comment]
Um, the optimize option was set to false / wasn't provided @lowlighter, not sure if it defaults to it but yea

**Comment by lowlighter** [comment]
`optimize` option defaults to `yes` and was introduced in v1.8 to let users disable it, since in prior versions this optimization was always run
