### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#179]
This workflow is failing on master: [here](https://github.com/Milo123459/Milo123459/runs/2061054775?check_suite_focus=true#step:2:1718)

**Comment by lowlighter** [comment]
You probably got unlucky and your workflow ran before the GitHub actions bot finished to rebuild indexes and new docker image 😕

**Comment by Milo123459** [comment]
Oh ahhaa, let me re try.
