### ISSUE TITLE
Cropping issue (activity plugin)

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#181]
![image](https://user-images.githubusercontent.com/50248166/110707395-2010b780-81f1-11eb-81b4-24bd5ba5f0f2.jpeg) it is splicing off the repository name, I am on mobile so that might be the issue

**Comment by lowlighter** [comment]
It's the same on desktop, probably need to add a wrap somewhere in it, but the activity ejs is kind of a mess 😅

**Comment by Milo123459** [comment]
Ah 🗡️
