### ISSUE TITLE
Don't use libxmljs

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#185]
Use a different XML parsing library then libxmljs that isn't required to build with node-gyp as it's failing on all of my servers and my laptop, not sure about others but yea.

[this](https://github.com/fb55/htmlparser2) might work

**Comment by lowlighter** [comment]
From what I remember, `node-gyp` requires python3:
https://github.com/lowlighter/metrics/blob/b0b16c929b0280198e2772836f6cdd1e6e37042c/Dockerfile#L26-L28

Need to check if htmlparser2 would fit
In the meantime the workaround is to either install required build utils for node-gyp, or install dev-dependencies separately after `npm ci --only=prod`

**Comment by Milo123459** [comment]
Let me see.
