### ISSUE TITLE
Overflow on website when using terminal template

### ISSUE THREAD

**Issue by kimlimjustin** [lowlighter/metrics#199]
Actually, this is a UI bug in the website and  I don't sure that is the website open-sourced or not, so I post this issue here. When choosing the terminal template, there's an overflow-x on the website. see this:
![Untitled](https://user-images.githubusercontent.com/61906684/112315598-db9b1680-8cdc-11eb-9952-11f748890a37.png)

I also figured out the way to fix this, edit the `margin` value of the `main>footer` tag to `1rem 0`, this will fix it :)
![Untitled](https://user-images.githubusercontent.com/61906684/112316075-582df500-8cdd-11eb-803c-c8f366cdb00e.png)

**Comment by lowlighter** [comment]
Yes the website is open-sourced too 🙂 (though the deploy is still manual)

I think your fix is located here:
https://github.com/lowlighter/metrics/blob/af843843f879dac60d53f2f14cbfa1c8b16cf1f5/source/app/web/statics/style.css#L271-L273

You can open a PR to patch it if you want, else I'll patch it when I have some time 👍🏼 
Thanks for the feedback!

**Comment by kimlimjustin** [comment]
Sure!
