### ISSUE TITLE
Can't open website in Chrome

### ISSUE THREAD

**Issue by kimlimjustin** [lowlighter/metrics#234]
Website is accessible in Firefox, but when opening in Chrome, it doesn't show anything, and when I open console, it shows up this:
![Screenshot from 2021-04-15 22-54-52](https://user-images.githubusercontent.com/61906684/114899938-9a120d00-9e3d-11eb-93ae-710ad92685e3.png)
![Screenshot from 2021-04-15 22-55-11](https://user-images.githubusercontent.com/61906684/114900014-a8f8bf80-9e3d-11eb-90e2-41025b346829.png)

However, there's no this error in FireFox

**Comment by lowlighter** [comment]
By any chance, did you visit the website on chrome previously?

If yes, could you try to reload with web console enabled and `disable cache` enabled in network tab to flush cache?
![image](https://user-images.githubusercontent.com/22963968/114924488-58c63100-9e2e-11eb-809a-65cee593fd3a.png)

I made some breaking changes on web instances, but not sure why a few cached scripts does not get updated so you still get the older scripts which doesn't work anymore 😕

**Comment by kimlimjustin** [comment]
Disabling cache makes it works! Thanks!
