### ISSUE TITLE
Merge commits are not condensed

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#241]
When merging commits form upstream, Metrics does not condense merge commits, instead spamming the recent activity section.

It would be better if Metrics removes all other commits if one of them matches "Merge branch Y into Z".

![Screenshot_20210419-094345](https://user-images.githubusercontent.com/42429413/115161851-03bb4100-a0f4-11eb-82c8-0597f9569ac5.png)

**Comment by Nixinova** [comment]
More of a feature request than a bug, I just didn't remove the label manually when creating (there's no "generic" issue template)

**Comment by Nixinova** [comment]
I assume this could be this be done by just adding something like:

```js
if (/Merged branch '.+?' into .+?/.test(commits[commits.length-1].message))
  commits = commits[commits.length-1];
```

to these lines:

https://github.com/lowlighter/metrics/blob/ec03286c90b7c1f6b4a1174a2106c362a9db7921/source/plugins/activity/index.mjs#L108-L111

**Comment by lowlighter** [comment]
Yes that would be nice 👍🏼 
I'm actually wondering if we should add a `.reverse()` too on the commits list, so pushed commits would appear from most recent to older instead

**Comment by lowlighter** [comment]
Thanks a lot for your contributions in #242 and #244 !
