### ISSUE TITLE
No packages are listed

### ISSUE THREAD

**Issue by ferferga** [lowlighter/metrics#302]
Hello!

[I have some packages listed under my account](https://github.com/ferferga?tab=packages). However, they're not shown in my user profile, despite the token having read rights for my packages.

![](https://raw.githubusercontent.com/ferferga/ferferga/main/github-metrics.svg)

I'm using the ``master`` branch, but error is also reproducible with ``latest`` and ``v3.9``

**Comment by lowlighter** [comment]
Hi!

Could you try out the following query on [GitHub GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) and post the return please 🙂 ?
```graphql
query {
  user(login: "ferferga") {
    packages {
      totalCount
    }
  }
}
```

It's quite strange, from what I remember accessing `totalCount` of packages doesn't require any additional token scope 🤔 

For some reason, even though I can [list your packages](https://github.com/users/ferferga/packages/container/package/selfhosted-mail-forwarding) from your profile page, when accessing detailed page your package count drops to 0:
![](https://user-images.githubusercontent.com/22963968/118526794-e30cf800-b740-11eb-9813-873ea0379ee8.png)

Which sould not from [what I reckon](https://github.com/users/ferferga/packages/container/package/selfhosted-mail-forwarding):
![](https://user-images.githubusercontent.com/22963968/118526743-d8526300-b740-11eb-9942-4660f8fd941b.png)

I tested in private browsing and got the same result for both 😕 
I think the GraphQL actually sent back the same result

But it's strange, I know that there is a visibility setting but if it was off I think others wouldn't see your packages

**Comment by ferferga** [comment]
Hmmm I'm getting 0 as well

I'll contact GitHub support and tell and update you with the information :). If you want you can close this issue, as it doesn't seem related to your action.

Thank you!

**Comment by lowlighter** [comment]
Ok, let me know in case you have any news about this 🙂
