### ISSUE TITLE
Footer generation time doesn't match timezone

### ISSUE THREAD

**Issue by ferferga** [lowlighter/metrics#304]
Hello!

Currently, even with a [timezone defined in the action settings](https://github.com/ferferga/ferferga/blob/main/.github/workflows/metrics.yml#L27), time in the footer is shown at GMT+0, instead of the user provided timezone.

**Comment by lowlighter** [comment]
Hi! 
Thanks for reporting, will be patched 👍

**Comment by ferferga** [comment]
Thank you for the quick fix!
