### ISSUE TITLE
Recent activity times are in UTC instead of the set timezone

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#324]
When displaying the timestamp of an activity the timezone is not passed to it so it displays in UTC.

![Screenshot_20210525-165211](https://user-images.githubusercontent.com/42429413/119441086-a4e38a00-bd79-11eb-874f-b1b4072481fb.png)

https://github.com/lowlighter/metrics/blob/5146305526a58ad86379b607dd44db5306e69cce/source/templates/classic/partials/activity.ejs#L166

The following I think would fix it (is `config` available directly in the partials?)
```diff
+ <%= f.date(timestamp, {timeStyle:"short", dateStyle:"short", timeZone:config.timezone}) %>
```

**Comment by lowlighter** [comment]
I checked quickly and it should be accessible through `config.timezone?.name` from within partials (`config.timezone` may be undefined if user didn't provide it)
