### ISSUE TITLE
Most used languages heading is centre aligned

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#328]
All the other headings use left alignment, making the languages heading out of place, and it clashes with the followup plugin subheadings.

![Screenshot_20210526-105501](https://user-images.githubusercontent.com/42429413/119578685-16bae280-be11-11eb-9669-9c2d899cf350.png)

**Comment by lowlighter** [comment]
Yeah it doesn't make sense anymore to keep it center-aligned.
I updated it so it'll look like more the current design of followup
