### ISSUE TITLE
🐞: Crop image where content ends

### ISSUE THREAD

**Issue by joe733** [lowlighter/metrics#33]
**Bug description**
Hi, There's a noticeable space after the content in the generated image.

**Expected behavior**
The image is cropped right after the content ends.

**To Reproduce**
Quite nothing, just make sure [metrics](https://github.com/lowlighter/metrics) is in the ReadMe. 🙂 

**Additional context and screenshots**

| Phone | Desktop | 
| --- | --- |
| ![photo_2020-12-31_12-58-16](https://user-images.githubusercontent.com/38415384/103399710-5cc49080-4b68-11eb-98f6-07e0c7d9b57e.jpg) | ![Screenshot from 2020-12-31 13-02-48](https://user-images.githubusercontent.com/38415384/103399758-8bdb0200-4b68-11eb-89d2-5ef79275196f.png) |

**Comment by lowlighter** [comment]
I'll look into it when I have some time.
I have a few leads to solve this but haven't tried them yet.

The workaround is to split your metrics into multiple images, but it's not very practical (it's because the padding mostly depends on enabled plugins)

**Comment by lowlighter** [comment]
It's better now, but it still needs some padding, will add it later

**Comment by lowlighter** [comment]
Should be fixed now. 
You can also use [`config_padding`](https://github.com/lowlighter/metrics#-other-options) option to adjust cropping/padding if needed (defaults to `6%`).

**Comment by joe733** [comment]
Superb, thanks!
