### ISSUE TITLE
GitHub Rest API v5 is broken

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#330]
Version: https://github.com/lowlighter/metrics/commit/8dafb854979c3f4f49c236da6c3e32a549735f00

#306 seems to have broken metrics generation:

```
at file:///metrics/source/app/action/index.mjs:131:40
undefined
An error occured, logging debug message :
Error: api.rest.request is not a function
Error: Process completed with exit code 1.
```

https://github.com/lowlighter/metrics/blob/8dafb854979c3f4f49c236da6c3e32a549735f00/source/app/action/index.mjs#L122
https://github.com/lowlighter/metrics/blob/8dafb854979c3f4f49c236da6c3e32a549735f00/source/app/action/index.mjs#L131

https://github.com/Nixinova/Nixinova/actions/runs/879627228

**Comment by lowlighter** [comment]
I reverted it, thanks for reporting 👍

**Comment by Nixinova** [comment]
(tagging #331)
