### ISSUE TITLE
Clipping error (mobile) in metrics insights

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#342]
Reported by @Nixinova in discussion #229

> Clipping error here (mobile)

<img src="https://user-images.githubusercontent.com/22963968/120066743-26883000-c078-11eb-9dfd-a8db2579013b.png" width="400">

Probably some css to change in [source/app/web/statics/about](https://github.com/lowlighter/metrics/tree/master/source/app/web/statics/about)

**Comment by Nixinova** [comment]
It's because the `.icon` uses `transform: scale(1.75)` which allows it to exit its container

**Comment by lowlighter** [comment]
I think the `transform` was used because upscaling svg was giving weird output, so I guess it's better to increase the margin
