### ISSUE TITLE
stackoverflow: Some questions have undefined comment counts

### ISSUE THREAD

**Issue by cherryblossom000** [lowlighter/metrics#344]
In the stackoverflow plugin, sometimes the comment count shows up as `undefined`. This is due to [a bug in the StackExchange API where `comment_count` is not always returned](https://stackapps.com/q/7021/48612).

<details>
<summary>Web instance demo: <a href="https://metrics.lecoq.io/cherryblossom000?template=classic&base.header=0&base.activity=0&base.community=0&base.repositories=0&base.metadata=0&stackoverflow=1&stackoverflow.user=8289918">https://metrics.lecoq.io/cherryblossom000?template=classic&base.header=0&base.activity=0&base.community=0&base.repositories=0&base.metadata=0&stackoverflow=1&stackoverflow.user=8289918</a></summary>

![](https://metrics.lecoq.io/cherryblossom000?template=classic&base.header=0&base.activity=0&base.community=0&base.repositories=0&base.metadata=0&stackoverflow=1&stackoverflow.user=8289918)
</details>

**Comment by lowlighter** [comment]
Indeed, seems that anwser formatter has `comment_count:comments = 0` to handle this bug, but the question formatter has no default:
https://github.com/lowlighter/metrics/blob/2ae690fac73120264a7221f821e0e708c11f3fc4/source/plugins/stackoverflow/index.mjs#L115

It would just need to append a `= 0` to default it when api doesn't return this field
