### ISSUE TITLE
Contributions calendar doesn't use specified timezone

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#354]
[These metrics](https://raw.githubusercontent.com/Nixinova/Nixinova/2752bfaf91338519234ae7bf9c854d613ed5944c/github-metrics.svg) show no commits on June 2 today but no empty square at the end of the contribs graph. [These](https://raw.githubusercontent.com/Nixinova/Nixinova/cd3118a3ea76ba6c4b8b2f888ce40fb3ff3d3510/github-metrics.svg) show two commits today but still no new day on the graph.

**Comment by lowlighter** [comment]
I've made some changes to directly set the `process.env.TZ` before spawning metrics
All occurences of `Date()` should use the timezone set in `config_timezone` now

**Comment by Nixinova** [comment]
Footer still uses UTC

**Comment by Nixinova** [comment]
https://github.com/lowlighter/metrics/commit/31315ad3a44d76b143c8456e94d895c6ecdc4aff didn't fix it

**Comment by Nixinova** [comment]
Footer is now accurate and I think the contribs graph is too
