### ISSUE TITLE
Error on render for achievements plugin

### ISSUE THREAD

**Issue by GalaxySH** [lowlighter/metrics#369]
This just seemed to happen without any interference from me. This has happened in at least the last 24 scheduled runs.

This is the error output:
![image](https://user-images.githubusercontent.com/34115400/121182500-c25c2d80-c828-11eb-958d-564d572c5d6d.png)

The options I have enabled:

                    plugin_achievements: yes
                    plugin_achievements_threshold: B       # Display achievements with rank B or higher
                    plugin_achievements_secrets: yes       # Display unlocked secrets achievements
                    plugin_achievements_ignored: octonaut  # Hide octonaut achievement
                    plugin_achievements_limit: 0

**Comment by lowlighter** [comment]
Since the achievement plugin use GitHub api you need a token, can you try using `token: ${{ secrets.METRICS_TOKEN }}` instead of `token: NOT_NEEDED` ?

It should work 🙂

**Comment by lowlighter** [comment]
Seems it has fixed it 👍
