### ISSUE TITLE
Documented anilist character limit option doesn't match generated action code

### ISSUE THREAD

**Issue by spenserblack** [lowlighter/metrics#378]
When the anilist plugin is enabled in https://metrics.lecoq.io/, the generated action code uses the option `plugin_anilist_limit.characters`. However, in [the latest documentation](https://github.com/lowlighter/metrics/blob/f5706746dad643e172b6192513b90f698b142781/source/plugins/anilist/README.md), it is `plugin_anilist_limit_characters`.

The last `_` is replaced with a `.`, basically.

**Comment by lowlighter** [comment]
Good catch!
