### ISSUE TITLE
526 http error

### ISSUE THREAD

**Issue by Javascript-Typescript** [lowlighter/metrics#382]
Hi!, I was trying to access to the page, and give me that cloudfare error.

**Comment by Zenoo** [comment]
The SSL certificate for [metrics.lecoq.io](https://metrics.lecoq.io/) seems to have expired

**Comment by lowlighter** [comment]
Sorry seems the auto-renewal cron is broken on my vps 😅 
Need to look at it, I renewed it in the meantime, you should be able to access without hassle it now 👍
