### ISSUE TITLE
Lines plugin output fluctuates

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#406]
The lines of code plugin's output fluctuates quite a bit, for instance here:

https://github.com/Nixinova/Nixinova/commit/27bf39d81e50ab3f186ee2042b506d77b441a003#diff-15c77d2bbedf6bd69a53f23e8705a32acfeeb9a45ca324f78e8f385924ab3f29R1322
```diff
- 231k added, 142k removed
+ 161k added, 85.3k removed
```

**Comment by lowlighter** [comment]
I don't known whether it comes from metrics or GitHub for this one.

There's nothing to fancy done in metrics, it's just a `rest.repos.getContributorsStats({owner, repo})` along with a `contributor.weeks.forEach(({a, d}) => (lines.added += a, lines.deleted += d))`.

It may be possible that this endpoint is similar to the search endpoint, where you could get partial/incomplete results.

Below's the full code for reference:
https://github.com/lowlighter/metrics/blob/f22a6d613c480e755ba9e330478a3a003b020858/source/plugins/lines/index.mjs#L20-L37
