### ISSUE TITLE
Make errors visible in workflow view

### ISSUE THREAD

**Issue by simonSlamka** [lowlighter/metrics#420]
Hi,

currently, errors thrown within individual jobs don't cause a failure of the job itself:
![image](https://user-images.githubusercontent.com/51794014/126441541-1cb98c9d-eb93-4098-82c0-30efb59990f1.png)

![image](https://user-images.githubusercontent.com/51794014/126441336-e45665ad-474b-4609-a906-2010582c3159.png)

This is very confusing and it can be difficult to find a job that failed.

**Comment by lowlighter** [comment]
Hello!

Currently this is mostly handled by `plugins_errors_fatal` where any error will cause the job to fail (though the partial rendering won't be pushed).

If I understand correctly, you wish to both display job as failed and push partial rendering ?

**Comment by simonSlamka** [comment]
Hey,

No, what I want is that the job will fail completely even though a partial rendering could be generated. As you can see in the example above, that error there causes the resulting image to be unusable because it contains an error and doesn't display any data. So if something like that happens, I want to terminate the job and not render anything.

**Comment by lowlighter** [comment]
Then setting `plugins_errors_fatal` to a `yes` or `true` should achieve what you want

![image](https://user-images.githubusercontent.com/22963968/126547330-7d33ff1b-2425-45ba-bf7b-35cdc5d98d76.png)

Reference: https://github.com/lowlighter/lowlighter/runs/3123647967?check_suite_focus=true#step:20:524

___

On a side note, seeing that we both got an error on github community support plugin I'd be tempted to say it has an issue that  needs to be fixed 🙂

**Comment by simonSlamka** [comment]
:-D yeah, though it was working yesterday. So something went wrong between yesterday and today morning
