### ISSUE TITLE
Member of organization count is not correct

### ISSUE THREAD

**Issue by Nirzak** [lowlighter/metrics#439]
Hi, I am a member of three organizations but the metrics showed 0, and also the number of my commit is 399 but the metrics showed it as 332.

**Comment by Nixinova** [comment]
Your profile doesn't show any organisations; check that your membership in them is set to public (its private by default).

**Comment by lowlighter** [comment]
For commits count, only last year was fetched, #440 will fix this.

As for memberships, like @Nixinova said above, only public memberships can be shown (if you check your github profile in "visitor" mode, you'll see that you're not being displayed as part of any organization). 
You can follow this [documentation](https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/organizations/memberships.md) to change this.

**Comment by Nirzak** [comment]
> For commits count, only last year was fetched, #440 will fix this.
> 
> As for memberships, like @Nixinova said above, only public memberships can be shown (if you check your github profile in "visitor" mode, you'll see that you're not being displayed as part of any organization).
> You can follow this [documentation](https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/organizations/memberships.md) to change this.

Oh ok understood.. So this issue can be closed I think.
