### ISSUE TITLE
Visual issues on metrics insights

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#450]
Some visual issues with metrics insights needs to be patched:

The S rank kept the drafted version instead of changes introduced in #435:
![image](https://user-images.githubusercontent.com/22963968/128242511-0b87b260-d01c-424e-b51a-d7dd1bf4d63b.png)
https://github.com/lowlighter/metrics/blob/403ccfd3cbcc1d86265219cd6e0f46c2ee9abd7d/source/app/web/statics/about/style.css#L365-L370

And the icons for closed issues and pull requests still points to the old octicons (needs to be updated with https://primer.style/octicons)
![image](https://user-images.githubusercontent.com/22963968/128242881-0ea34672-f510-4820-9b14-6f79b49f2a74.png)

https://github.com/lowlighter/metrics/blob/403ccfd3cbcc1d86265219cd6e0f46c2ee9abd7d/source/app/web/statics/about/index.html#L190-L193

https://github.com/lowlighter/metrics/blob/403ccfd3cbcc1d86265219cd6e0f46c2ee9abd7d/source/app/web/statics/about/index.html#L208-L211

**Comment by spenserblack** [comment]
Regarding keeping achievement rank colors consistent, you might be able to keep the CSS styling that's also needed in JS in a constants file. That way you wouldn't have to remember to edit both `source/plugins/achievements/index.mjs` and `metrics/source/app/web/statics/about/style.css`. You might be able to do this with a language that compiles to CSS.

For example, it looks like Stylus supports [importing values from JSON](https://stylus-lang.com/docs/bifs.html#jsonpath-options) or [defining functions with JavaScript](https://stylus-lang.com/docs/bifs.html#usepath).

**Comment by lowlighter** [comment]
Yeah usually I go with Less, but got too lazy to setup it 😕 Maybe one day
