### ISSUE TITLE
Broken formatting on discussions

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#461]
![image](https://user-images.githubusercontent.com/50248166/128665759-f69d7d2e-2c35-427f-8a10-bc0c3778eb3b.jpeg)

Text is off center and gets cut off in mobile

**Comment by lowlighter** [comment]
@Milo123459 Which browser / OS are you using on mobile ? 
It seems fine on the GitHub iOS app but I can try to reproduce on other platforms with more infos.
Also do you known if it's impacting both emojis and twemojis ?

**Comment by Milo123459** [comment]
I'm on GitHub iOS latest. And no I don't know if it's both.

**Comment by lowlighter** [comment]
Seems to only affect twemojis
