### ISSUE TITLE
Repositories plugin breaks followup plugin and languages plugin

### ISSUE THREAD

**Issue by TheNetAdmin** [lowlighter/metrics#488]
Hi, I just found the *repositories* plugin breaks the *followup* plugin and the *languages* plugin.

## Enable repositories plugin
Once the *repositories* plugin is enabled, the other two plugins show no result (Link to [the commit and svg](https://github.com/TheNetAdmin/TheNetAdmin/blob/5efe0be1f9100f078a10a5075870b444a1d9e81f/github-metrics.svg)):

![image](https://user-images.githubusercontent.com/18525442/129964790-49c27429-b64d-4c53-8e86-74f04bfa2d9b.png)

## Disable repositories plugin
If I disable *repositories*, the other two works fine (Link to [the commit and svg](https://github.com/TheNetAdmin/TheNetAdmin/blob/4e2f2dcfc96c80e23b49b70d11345563e5c7992b/github-metrics.svg)):

![image](https://user-images.githubusercontent.com/18525442/129964756-456673c2-64c6-451b-93a0-1a236d60c0ad.png)

**Comment by lowlighter** [comment]
Hum I'm not able to reproduce it (at least with my account), maybe another occured in the meantime or another config option is responsible of it?

If you still have the workflow which resulted in this state somewhere, could you paste it here?

**Comment by TheNetAdmin** [comment]
> Hum I'm not able to reproduce it (at least with my account), maybe another occured in the meantime or another config option is responsible of it?

I can still reproduce it (a few secs ago), not sure why
 
> If you still have the workflow which resulted in this state somewhere, could you paste it here?

The link to [the commit](https://github.com/TheNetAdmin/TheNetAdmin/tree/0f5f065ed95329cf1ec6f8804b06bb741c584268)

And [workflow code](https://github.com/TheNetAdmin/TheNetAdmin/blob/0f5f065ed95329cf1ec6f8804b06bb741c584268/.github/workflows/metrics.yml)

**Comment by lowlighter** [comment]
@TheNetAdmin Thanks, I can indeed reproduce with what you provided, will check 👍
