### ISSUE TITLE
Merge commit not skipped in language stats

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#502]
I found random language 'TCL' in my language stats this morning:
![image](https://user-images.githubusercontent.com/42429413/131043785-54415393-32e0-4aa3-9a2d-6d0cb31d671a.png)

I was thinking this was an issue on my end but found this merge commit yesterday:
![image](https://user-images.githubusercontent.com/42429413/131043833-13f37336-ef65-4d1c-892e-aabacbc056ef.png)
It added a [666 SLOC file](https://github.com/github/linguist/blob/f56a04e0d6d428ce2b2f3f02e7fd9918b9bbc572/samples/Tcl/init.tcl.in) (https://github.com/github/linguist/commit/f56a04e0d6d428ce2b2f3f02e7fd9918b9bbc572), which metrics doesn't seem to have skipped.

**Comment by Nixinova** [comment]
> it looks like commits have a "parents" key. Merge commits typically have two parents

So would the best option to fix this be adding this line here?
https://github.com/lowlighter/metrics/blob/c70b6493c0526f13689b557aa96aa468d1a5c400/source/plugins/languages/analyzers.mjs#L55-L59
```js
            .filter(({parents}) => parents.length < 2)
```

**Comment by lowlighter** [comment]
Yes it seems 👍 
Mocked events probably needs to be patched too, I don't think the `commit.parents` are in them so tests would fail
