### ISSUE TITLE
Isocalendar is unable to count streak after 182 in half mode.

### ISSUE THREAD

**Issue by Tarun-Kamboj** [lowlighter/metrics#512]
My actual streak :
![](https://github-readme-streak-stats.herokuapp.com/?user=Tarun-Kamboj&theme=dark)
Isocalendar showing :
![](https://github.com/Tarun-Kamboj/Tarun-Kamboj/raw/master/Images/Dynamic/isocalendar.svg)

**Comment by Nixinova** [comment]
That's cause your calendar is on half year mode. It doesn't load anything from more than 365/2=182 days ago.

**Comment by Nixinova** [comment]
Maybe a check could be added like ` if (streak >=  181) streak += "+" ` though to help.

**Comment by lowlighter** [comment]
I think it's worth to get the accurate number. 

To save queries we can fetch further data only when the streak is complete like in this case

**Comment by lowlighter** [comment]
This will be available with 3.14 👍
