### ISSUE TITLE
Languages plugin with empty result

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#513]
Ref: #511

Seems in some case the languages plugin returns an empty result

Need to investigate

**Comment by Nixinova** [comment]
Copying the relevent comments:

<hr>

@Nixinova https://github.com/lowlighter/metrics/pull/511#issuecomment-909706194
> Hm, this merge seems to have broken the languages plugin, `await linguist(path)` returns nothing:
> ![image](https://user-images.githubusercontent.com/42429413/131585823-b856029d-3c24-451c-853e-14a4c78cb7c6.png)
> ![image](https://user-images.githubusercontent.com/42429413/131585871-09f7287f-5f5a-4bca-a4a6-ade8a58d7aa5.png)
> 
> I don't see where this would have broken, though, since it seems to be working perfectly fine for me, even when using a Linux subsystem:
> ![image](https://user-images.githubusercontent.com/42429413/131585766-7549b4ba-557c-4ead-9ebe-8dd5d138c76a.png)
> 🤔 🤔

<hr>

@lowlighter https://github.com/lowlighter/metrics/pull/511#issuecomment-910523783
> I don't think it's globally broken, mine still seems to be up (it was refreshed 2h ago)
> 
> Will try to investigate about it later 👍

<hr>

@Nixinova https://github.com/lowlighter/metrics/pull/511#issuecomment-912070370
> Huh, this is weird.
> 
> ![Screenshot_20210903-092553](https://user-images.githubusercontent.com/42429413/131918401-4cab6e96-80d6-4c19-8922-9c002ee51ccf.png)
> 
> #502 also doesn't appear, double weird...

**Comment by Nixinova** [comment]
Seems to be an independent issue, https://github.com/Nixinova/Nixinova/commit/d3719c345d72eb3d2ead0a2f1dcdf945fa7bd0d7 was generated with e3cd805fa480071232fd4bff35565251bafaf263 (Aug 26) which was working prior.

**Comment by Nixinova** [comment]
Also typo in issue title: 'Langage'

**Comment by Nixinova** [comment]
Now crashes with `TypeError: Cannot read property 'length' of undefined
            at file:///metrics/source/plugins/languages/analyzers.mjs:81:34`

**Comment by lowlighter** [comment]
> Seems to be an independent issue, Nixinova/Nixinova@d3719c3 was generated with e3cd805 (Aug 26) which was working prior.

The latter seems to be caused because of how paths were reported (not sure whether it's git or linguist which changed), but one was absolute and the other relative to the repository. Also on windows the paths used partially `\\` instead of `/`

> Now crashes with TypeError: Cannot read property 'length' of undefined at file:///metrics/source/plugins/languages/analyzers.mjs:81:34

This was introduced because of #517, but should be fix now 👍

**Comment by Milo123459** [comment]
Still getting this issue: https://github.com/Milo123459/Milo123459/runs/3527913159?check_suite_focus=true

I had 18 emails.. 😆

**Comment by Nixinova** [comment]
I've got a fix for that crash coming up

**Comment by Milo123459** [comment]
> I've got a fix for that crash coming up

Woo! Can't wait. Currently had to switch to `latest` branch to suppress emails. :(

**Comment by thib3113** [comment]
The MR seems to doesn't resolve the problem : 
```
file:///metrics/source/plugins/languages/analyzers.mjs:172
            if (!categories.includes(languageResults[lang].type))
                                                           ^

TypeError: Cannot read property 'type' of undefined
    at Interface.stdout (file:///metrics/source/plugins/languages/analyzers.mjs:172:60)
    at Interface.emit (node:events:394:28)
    at Interface._onLine (node:readline:487:10)
    at Interface._normalWrite (node:readline:661:12)
    at Socket.ondata (node:readline:269:10)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by Milo123459** [comment]
Is this now fixed?

**Comment by thib3113** [comment]
@Milo123459 not sure ... on my side it doesn't crash ... But "locale" part is now totally empty ... ( https://gist.githubusercontent.com/thib3113/83a96e16f8bca103f1b0e376186c66ec/raw/github-metrics.svg )

**Comment by lowlighter** [comment]
@Milo123459 @thib3113 Currently only the crash issue has been fixed, but the initial issue is remaining

___

I debugged a bit and it seems to come from here:
https://github.com/lowlighter/metrics/blob/af8c476548f0528f62203d1896c1536a17e61656/source/plugins/languages/analyzers.mjs#L142-L144

I'm not sure but I think it's an issue with linguist. 

Seems that despite the repository path is correctly given (in this case `/tmp/22963968-lowlighter_itsudeno`) it looks for files in the first processed repository (in this case `/tmp/22963968-lowlighter_metrics/`)
```
DEBUG | repository to analyze /tmp/22963968-lowlighter_itsudeno
Error: ENOENT: no such file or directory, lstat '/tmp/22963968-lowlighter_metrics/.dockerignore'
    at Object.lstatSync (node:fs:1514:3)
    at analyse (/metrics/node_modules/linguist-js/dist/index.js:106:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async analyze (file:///metrics/source/plugins/languages/analyzers.mjs:147:72)
    at async indepth (file:///metrics/source/plugins/languages/analyzers.mjs:32:7)
    at async Object.default [as languages] (file:///metrics/source/plugins/languages/index.mjs:72:34)
    at async file:///metrics/source/plugins/core/index.mjs:50:30
    at async Promise.all (index 0)
    at async metrics (file:///metrics/source/app/metrics/index.mjs:61:22)
    at async file:///metrics/source/app/action/index.mjs:292:24 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/tmp/22963968-lowlighter_metrics/.dockerignore'
}
```

Seems that only the first repository can be correctly processed.

Languages results may still be empty if the first repository processed contains only `data`/`prose` languages (like YAML or markdown) which are ignore by default.

The error thrown by linguist-js seems to be have fixed in 2.0.2 but it's weird that it is looking for a file of a separate repository 🤔
 @Nixinova do you have more insight about this?

**Comment by Nixinova** [comment]
The lstat issue is Nixinova/Linguist#4 but I'm not sure why it would be looking in a different directory. I'd have to have the full linguist-js output to know.

**Comment by lowlighter** [comment]
Upgrading to linguist latest version seems to have fixed it 👍
