### ISSUE TITLE
Bars on full-year calendar are too short

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#530]
The bars in the isocalendar plugin are too short when set to full-year mode which removes the 3D effect:

| Half-year | Full-year |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/42429413/132648514-20488e53-5a2d-4095-a87f-12411b12c0fa.png) | ![image](https://user-images.githubusercontent.com/42429413/132648555-f6e32489-1a74-4686-b262-993304a77e86.png) |

**Comment by lowlighter** [comment]
Will be fixed by #532 👍 
It's because it used all-time max instead of max in given time frame
