### ISSUE TITLE
GitHub Action running error

### ISSUE THREAD

**Issue by gd1214b** [lowlighter/metrics#538]
Log:
<https://github.com/gd1214b/cdn/runs/3608167273?check_suite_focus=true>

**Comment by spenserblack** [comment]
You used options like `plugin_repositories_affiliations`, etc. These base options don't have `plugin_` at the start. See [the documentation for base options](https://github.com/lowlighter/metrics/blob/master/source/plugins/base) for the correct value names.

Also, this should probably be moved to Q&A discussions :slightly_smiling_face:
