### ISSUE TITLE
Adding organization for languages and repos by changing option

### ISSUE THREAD

**Issue by Napolitain** [lowlighter/metrics#59]
In file https://github.com/lowlighter/metrics/blob/master/source/queries/repositories.graphql we have the request for gathering repos and its related languages.

I think we remove here OwnerAffiliations as we already have isFork line as here : `repositories($after first: $repositories, isFork: false, ownerAffiliations: OWNER, orderBy: {field: UPDATED_AT, direction: DESC}) `.

Both of them seem redundant as if we don't fork, we can't not be owner. Those settings include then organizations and maybe even the projects in which you collaborate but that are not fork (collaborator in friend's project comes to mind).

I can't try pull request right now but I suggest exploring this area, I tried some differences in GraphiQL explorer and it seems pretty good.

**Comment by lowlighter** [comment]
Hello !

Yes I'll take a look at it, I know we talked a bit about it in #8 but haven't digged into it too much since 👍

**Comment by lowlighter** [comment]
I removed `ownerAffiliations` constraint with #61 so now metrics should include repositories you contributed, whether you own them directly or not 👍

**Comment by lowlighter** [comment]
Next version (and current `@master`) will have filter changed back to `owner` as it seems to cause issues (#120 #115).
It's probably related to the fact that `organization_member` is too broad for large organizations and even include repositories you never contributed.

You'll still be able to use new option `repositories_affiliations` with an empty value (`""`) to disable filtering and have same behaviour as #61
