### ISSUE TITLE
Plugins timeout for "huge users"

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#598]
This is a follow-up of #584

Since each plugin are independant (except for the `base` one which is required and has been patched in #584), some plugins may still have GitHub API timeouts, reported by the following message:

> Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include XXXX:XXXX:XXXXXX:XXXXXX:XXXXXXXX when reporting this issue

This issue will be used to track these faulty plugins and eventually change their queries to make them work for "huge users"

If you encounter this issue on a plugin not listed below, don't hesitate to post it here (and tell on which user it occurs if it's not yourself) so it can eventually be patched

____

Plugins:
- [x] base
- [x] reactions -> (this one skips errors but should auto-fix itself when graphql api won't fail for issues endpoints)
- [x] followup -> (should be fixed with refacto of this plugin which also added `indepth` in #627)
- [x] isocalendar

**Comment by jayvdb** [comment]
Just noting I havent seen any problems with followup or isocalendar. Only reactions is failing.

I've also tried a simple query in https://docs.github.com/en/graphql/overview/explorer , and get back unicorns. All variations of the following fail.

```graphql
query ReactionsDefault {
  user(login: "jayvdb") {
    login
    issues(last: 1) {
      edges {
        node {
          reactions(last: 1) {
            nodes {
              user {
                login
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jayvdb** [comment]
So .. how does https://github.com/vvo/sourcekarma/ do it ?  https://github.com/vvo/sourcekarma/issues/18 prevents me from seeing if it has similar problems.

**Comment by lowlighter** [comment]
> Just noting I havent seen any problems with followup or isocalendar. Only reactions is failing.

Yeah it really depends on user. #645 reported that there are issue with the followup for example

> So .. how does https://github.com/vvo/sourcekarma/ do it ? vvo/sourcekarma#18 prevents me from seeing if it has similar problems.

Hum I'm not sure actually, last time I checked I was not able to find the relevant code (I think only the vercel web app is exposed but I'm not sure).

It's possible that the REST api is used instead, but I don't know.
However the GraphQL failing for a single issue is definitely a GitHub bug, I don't think it's expected to timeout for a simple query

**Comment by gaocegege** [comment]
Should we ask for GitHub Help?

**Comment by lowlighter** [comment]
Maybe for the reaction query yeah

**Comment by gaocegege** [comment]
I opened one ticket for it. Will keep track of the process here.

**Comment by gaocegege** [comment]
Here is the response from GitHub support:

Thanks for reaching out.

I took a look at the logs and it seems you're hitting timeouts on our end even on that simple query.

There's anything you can do about the timeout and I think this is something the team on our end needs to look at and see what we can do to optimize the execution of that query --so I have passed this specific feedback along to them. I can't promise an ETA, but we'll follow up if there's any news.

Regards,

GitHub Support

**Comment by lowlighter** [comment]
Nice, thanks a lot for reaching them and let us know that they'll eventually work on it!

**Comment by lowlighter** [comment]
Mentioned plugins were updated to support users with larger amount of data as far as possible.
Also the query used by the reaction plugins seems to have been fixed by GitHub 

I'll close this issue, if you encounter other issue related to timeout you can report them back into discussions so it gets investigated 👍
