### ISSUE TITLE
Add a new `icons` mode titled with starred topics title instead of mastered

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#638]
### Discussed in https://github.com/lowlighter/metrics/discussions/636

<div type='discussions-op-text'>

<sup>Originally posted by **abrahamnm** October 29, 2021</sup>
While setting up my yaml file I realized that the Topics plugin maybe doesn't have the most appropriate title when you want to display icons instead of labels.

I have starred many projects that interest me in different technologies and languages, but that doesn't necessarily mean that I am a master and know them.

English is not my native language, so I don't know if it's the best choice, but "Technologies and topics of interest" might be an option.</div>

**Comment by Nixinova** [comment]
It seems most of the new discussions are being turned into issues, so I think it may be better to switch back to allowing issues to be opened directly.

**Comment by lowlighter** [comment]
> It seems most of the new discussions are being turned into issues, so I think it may be better to switch back to allowing issues to be opened directly.

I actually like this system since it's kind of a "filter" and make issues really something that'll be eventually working on (kind of a validated bugs/features with no definite ETA). I find it also less intimidating for new users as they don't have risk to have their issues insta-closed since discussion have no definite state
