### ISSUE TITLE
Code plugin includes merges of other peoples code

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#646]
### Discussed in https://github.com/lowlighter/metrics/discussions/639

<div type='discussions-op-text'>

<sup>Originally posted by **jayvdb** October 30, 2021</sup>
The [code plugin](https://github.com/lowlighter/metrics/tree/master/source/plugins/code) includes snippets authored by others which are a merge commit.

e.g. my [current snippet](https://github.com/jayvdb/jayvdb/commit/9dabff00eac6842f0f1a0a3febc97d44aec6d6d2) is from https://github.com/jayvdb/pypidb/commit/2af9d402b81da6aa5598ea6e1d5015b48a75d20d , which is a bog standard merge of https://github.com/jayvdb/pypidb/pull/120
</div>

**Comment by jayvdb** [comment]
Actually ... it is including other peoples commits, completely unrelated to the author.

https://github.com/jayvdb/jayvdb/commit/6b8c7f5e003ceb1234994f56ea506b989171417d is a snippet from https://github.com/jayvdb/conan-center-index/commit/d5ce1ed4 .  That commit was pulled into my branch when I rebased https://github.com/conan-io/conan-center-index/pull/6560

I guess that this line isnt doing what it is suppose to:
```js
.filter(({author}) => data.shared["commits.authoring"].filter(authoring => author?.email?.toLocaleLowerCase().includes(authoring)||author?.name?.toLocaleLowerCase().includes(authoring)))
```

A way to address this specific type of problem is to exclude forks from the `code` plugin.

**Comment by spenserblack** [comment]
If I'm reading that JS line correctly, it's filtering based on the results of a filter. Which wouldn't do any filtering, since all results of a filter, including an empty array, are truthy. `!![] === true`
Should the inner filter be a `.some` instead?

**Comment by lowlighter** [comment]
> If I'm reading that JS line correctly, it's filtering based on the results of a filter. Which wouldn't do any filtering, since all results of a filter, including an empty array, are truthy. !![] === true

Yeah indeed, it was missing the `.length` on the empty array
