### ISSUE TITLE
Optimize and purge unused CSS

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#662]
Currently a template is only composed of a single CSS file (the original goal was to be consistant across all plugins, though some plugins are so much different from others that they need additional rules).

While I think conditionally including rules is a bad idea in current design, it's probably a good idea to purge unused CSS and run a minifier on remaining CSS to reduce file size.

The following libs seems to be popular and still maintained:
- [FullHuman/purgecss](https://github.com/FullHuman/purgecss)
- [css/csso](https://github.com/css/csso)

**Comment by Milo123459** [comment]
Vouch for purgecss, super useful
