### ISSUE TITLE
`plugin_music`: Album cover size consistency

### ISSUE THREAD

**Issue by matievisthekat** [lowlighter/metrics#684]
The sizes of the album covers are not constant. (see images below

| Good size | Too big |
| :---: | :---: |
| ![Screenshot from 2021-11-28 11-32-20](https://user-images.githubusercontent.com/45036977/143762593-c520d537-4fea-4125-bceb-f5aeca1a1cc4.png) | ![Screenshot from 2021-11-28 11-32-35](https://user-images.githubusercontent.com/45036977/143762632-f445f330-484f-4024-9d3c-e04547b9dce9.png) |

Both are showing 5 songs, but the recently played section has much larger album covers.

I'm not sure, but this seems like it may be related to the name length of the last song (`The Song with Five Names a.k.a. Soapbox Tao a.k.a. Checkmate Atheists! a.k.a. Neospace Government (A.K.A. You Can Never Know)`). All the other song names fit on 1 line. This is the only one that doesn't

Maybe the song name should cut off instead of flowing over to the next line?

**Comment by matievisthekat** [comment]
Update: This issue doesn't seem to be caused by the text overflowing.

Reason: with the fix implemented in #685 the album covers are still too large
| Original | Updated |
| :---: | :---: |
| ![original](https://user-images.githubusercontent.com/45036977/143762632-f445f330-484f-4024-9d3c-e04547b9dce9.png) | ![Screenshot from 2021-11-28 12-01-18](https://user-images.githubusercontent.com/45036977/143763561-6a70d8dc-b908-4c6e-9984-f3d97912fef4.png) |

**Comment by matievisthekat** [comment]
The issue is caused by this line:
```ejs
<img src="<%= artwork %>" width="<%= plugins.music.played_at && played_at ? 48 : 32 %>" height="<%= plugins.music.played_at && played_at ? 48 : 32 %>" alt=""/>
```
although this shows it isn't an issue... but rather a design choice.

That leads me to question this design choice. I am using both top and recent music plugin configurations, and this inconsistency looks less than appealing (I'm my opinion).

**Comment by matievisthekat** [comment]
For example, this
<img src="https://user-images.githubusercontent.com/45036977/143764702-d8428dd3-d0bc-4eec-9736-b8fffa7fd6d1.png" width="600" />
looks most consistent than
<img src="https://user-images.githubusercontent.com/45036977/143764826-63a1e39c-1352-47c1-bef1-7e7540a8d3c7.png" width="600" />

**Comment by lowlighter** [comment]
Yeah I agree that keeping the same size is better design
