### ISSUE TITLE
`output_action: none` is completely ignored

### ISSUE THREAD

**Issue by muxinqi** [lowlighter/metrics#698]
### Discussed in https://github.com/lowlighter/metrics/discussions/642

<div type='discussions-op-text'>

<sup>Originally posted by **ferferga** November  1, 2021</sup>
I still get commits even when I have that option set as none.

I'm using ``latest``.</div>

I tried both `latest` and `main` versions of metrics separately, it still push a commit for me when I set `output_action` to `none`.

I've tried to figure this out in `debug` mode, but still get no luck.

You can see more information here:
https://github.com/muxinqi/muxinqi/runs/4417795903

**Comment by muxinqi** [comment]
I create a minimal repo to reproduce.
https://github.com/muxinqi/test-metrics

**Comment by lowlighter** [comment]
Thanks for your report, will take a look at it this week 👍
