### ISSUE TITLE
Can't get my github metrics

### ISSUE THREAD

**Issue by lionelsamrat10** [lowlighter/metrics#714]
### Discussed in https://github.com/lowlighter/metrics/discussions/713

<div type='discussions-op-text'>

<sup>Originally posted by **lionelsamrat10** December 14, 2021</sup>
When I am trying to fetch my metrics, it is showing like that: An error occurred while generating metrics :(
Internal Server Error: failed to process metrics correctly</div>

**Comment by matievisthekat** [comment]
would you be able to get the error that was logged in the workflow run? (assuming you're generating the metrics in a workflow)

**Comment by lionelsamrat10** [comment]
It's sorted. Thank you!!
