### ISSUE TITLE
Support retries on pushing process

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#728]
Currently `retries` are only possible for rendering.
Some "failed to push" situations could be resolved with retries too but it's not possible yet. 
Probably should have an option like `retries_output_action` or something similar

**Comment by matievisthekat** [comment]
I agree this could be useful, but I think automatically retrying **only** when [this issue](https://github.com/lowlighter/metrics/discussions/727#discussion-3760887) occurs is worth considering as well. Unless there are other reasons to retry pushing, of course.

I feel like it might result in some irrational retrying (if the token doesn't have write permissions for example)

**Comment by lowlighter** [comment]
Yeah I agree

There at least the other case where "a secondary rate limit was reached" (I often get this one) for huge workflows

We could just check the error message and handle at least these twos in a first tome
