### ISSUE TITLE
Restricts average commits per day by fetched data

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#753]
### Discussed in https://github.com/lowlighter/metrics/discussions/743

<div type='discussions-op-text'>

<sup>Originally posted by **developomp** January  6, 2022</sup>
I have around 1500 commits pushed in the last 365 days, most of which are concentrated in the last couple of months. However, the average commits per day is 1.44 when it should be at least 4. Why is this the case?

Here's my GitHub profile: https://github.com/developomp
</div>

**Comment by JayantGoel001** [comment]
@lowlighter Assign me this issue.

**Comment by developomp** [comment]
Or better yet, only work with the data shown in the isocalendar. That is, parsing only 6 months worth of data for half size and 12 months worth of data for full size calendar.
