### ISSUE TITLE
Add language percentages to classic template

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#85]
It would be useful to have something like this available for use in the classic template:

![](https://github-readme-stats.vercel.app/api/top-langs/?username=Nixinova&langs_count=8&layout=compact&theme=radical)

The percentages are already in the terminal template and it would be good to have the percentages available in classic as well.

**Comment by lowlighter** [comment]
Added with #87 👍

**Comment by Nixinova** [comment]
Will this option be available on the web instance as well?

**Comment by lowlighter** [comment]
Yes it's available on shared web instance since it does not consume too much query 🙂

**Comment by Nixinova** [comment]
The URL query parameter works, but the config option doesn't show up in the list.

**Comment by lowlighter** [comment]
It's there but I confess param name isn't very clear. 
Placeholder binding may be broken, I'll take a look at it

![image](https://user-images.githubusercontent.com/22963968/107068629-25897500-67e1-11eb-97c3-9c9bfb0601dc.png)
