### ISSUE TITLE
Add WakaTime plugin

### ISSUE THREAD

**Issue by AndrewDaGuy** [lowlighter/metrics#86]
Add a <code>wakatime</code> plugin which integrates  with the [Wakatime API](https://wakatime.com/developers/).

**Comment by lowlighter** [comment]
I'll add it to [Roadmap and todos](https://github.com/lowlighter/metrics/projects/1) 👍 
Thanks for your suggestion

**Comment by lowlighter** [comment]
[⏰ WakaTime plugin](https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md) is now available on `@master` branch. 

It'll be on `@latest` on a few weeks on next release 👍
