### ISSUE TITLE
Error 502 - Bad Gateway

### ISSUE THREAD

**Issue by phaticusthiccy** [lowlighter/metrics#868]
### Discussed in https://github.com/lowlighter/metrics/discussions/867

<div type='discussions-op-text'>

<sup>Originally posted by **phaticusthiccy** February 10, 2022</sup>
Sometimes the site downs. You can search for a solution.

![Ekran Görüntüsü (181)_LI](https://user-images.githubusercontent.com/74794033/153427971-6f050281-b95f-4105-ab40-afe1d12a6387.jpg)
</div>

**Comment by lowlighter** [comment]
Restarted the service which is now up again.
Closing for now
