### ISSUE TITLE
fix(plugins/languages): EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#873]
### Discussed in https://github.com/lowlighter/metrics/discussions/869

Seems the languages plugin in `indepth` mode sometimes attempts to `readFile` cloned directory instead.
Anyway the error is not properly caught since it's the main rejection handler that get it instead of dying nicely

**Comment by Nixinova** [comment]
Would this be a problem with linguist-js? If so this wouldve been fixed in 2.2.1 https://github.com/Nixinova/Linguist/commit/5c6b1813b2a9cc93f0a6ecc38daa1fd8d08768da

**Comment by lowlighter** [comment]
We could try updating the linguist-js indeed, seems to still be on 2.2.0 currently so maybe it'll solve the issue.

Tbh I wasn't able to reproduce the mentioned bug yet

**Comment by Nixinova** [comment]
this issue should no longer occur with #882  & 108b40f94afa1aa7673c6a3eb8f0f592d0f69d74 as theres no disk ops anymore

**Comment by lowlighter** [comment]
Closing as no user seems to recently have encountered this issue
