### ISSUE TITLE
fix(plugins/stargazers): `chartist` mode does not display values

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#888]
### Discussed in https://github.com/lowlighter/metrics/discussions/884

When in `chartist` mode, each point value should be displayed but it currently doesn't

**Comment by lowlighter** [comment]
I think this is only the case when using `embed()` function

Regular one is working expected. 
Probably related to the fact that values are post processed

**Comment by Andre601** [comment]
Any possible fix to this yet?

**Comment by lowlighter** [comment]
Should be fixed by #954, seems it was just missing a class which made the post-processing have no effects
