### ISSUE TITLE
plugin_music with Spotify does not play

### ISSUE THREAD

**Issue by Minghao2812** [lowlighter/metrics#897]
### Discussed in https://github.com/lowlighter/metrics/discussions/896

<div type='discussions-op-text'>

<sup>Originally posted by **Minghao2812** February 17, 2022</sup>
Hi @lowlighter and all the contributors to this project! Thanks for bringing such an impressive tool for creating dynamic profile pages! My plugin_music with Spotify does not play my song when I visit my profile page, and I'm not sure if I setup it wrong. My profile page looks like this:
![image](https://user-images.githubusercontent.com/57082435/154449981-20ceead7-ad03-403f-bf60-9f4e3e4cb83a.png)

And the Action code looks like this:
```
## plugin: music
plugin_music: yes
plugin_music_provider: spotify
plugin_music_token: "***************************************, ****************************************, *******************************************************************"
plugin_music_mode: playlist
plugin_music_playlist: https://open.spotify.com/embed/playlist/*****************************
```

Would you or any contributors like to kindly help me with this?

Many thanks,

Minghao</div>

**Comment by Nixinova** [comment]
see discussion in #896 - this issue was unnecessarily split off
