### ISSUE TITLE
fix: grammatical errors

### ISSUE THREAD

**Issue by PeterNjeim** [lowlighter/metrics#904]
There are several instances of "an user" in the README, these should all be "a user" instead. "An user" sounds clunky, due to "user" starting with a consonant sound, which defeats the purpose of the "n" in "an", which is designed to smoothly transition from the vowel sound "a" in "a" to a word that starts with a vowel sound, like "organisation".

**Comment by DalpatRathore** [comment]
How many instances of this grammatical article "an user" mistake did you notice. I have seen 4 instances, as can be seen in screenshots. 
- Follow-up of issues and  People plugin - **3** mistakes
 ![cap1](https://user-images.githubusercontent.com/69510006/154997968-dc37bcf6-f2e4-45b7-8a89-843c39b30e23.JPG)

-   Introduction - **1** mistake
 ![cap-2](https://user-images.githubusercontent.com/69510006/154997983-000640f4-13d5-44d8-8dc3-866c69ec5f46.JPG)

**Comment by lowlighter** [comment]
Yeah it's entirely possible, I confess that I don't know the exact rule behind it. 
School told me to use "an" instead of "a" if next word starts with a vowel 😅 

PR to correct these is welcomed 👍

**Comment by PeterNjeim** [comment]
Vowel sound, not vowel letter, or else it wouldn't really make too much sense. "User" starts with a consonant sound "**y**oo-zir", so you use "a" and not "an" to make it smoothly transition and easy to say. "Umbrella" starts with a vowel sound "**u**m-brel-la", so it's "an umbrella" and not "a umbrella". You don't need to "remember the rule" or anything, it's quite literally whatever's the easiest to say.

PR: #910
