### ISSUE TITLE
fix(plugins/base): displayed contributions limited to last year

### ISSUE THREAD

**Issue by renbaoshuo** [lowlighter/metrics#951]
![image](https://user-images.githubusercontent.com/47095648/159117152-b6cb9d0a-c7b3-4a41-ac6f-c2ec665cc045.png)

Commits was displayed correctly in metrics. But counts of pull requests and issues were only displayed from last year, not all.

![](https://user-images.githubusercontent.com/47095648/159117110-07ad5f48-7082-45bb-be29-79c67f9b563a.png)

---

Some references that might be helpful in fixing this:

1. https://stackoverflow.com/questions/64619444/in-github-graphql-what-is-the-difference-between-contributioncollection-totalp
2. https://docs.github.com/en/graphql/reference/objects#user
3. https://docs.github.com/en/graphql/reference/objects#contributionscollection

**Comment by lowlighter** [comment]
I think the best would be to use `contributionsCollection(from: "", to: "") {}` (i.e. with a time-span) to solve this issue

The reasoning behind is that some fields from contributions collection are not available directly (e.g. reviews, commits, etc.) and using directly `totalCount` for large users almost always end up in API timeouts

**Comment by renbaoshuo** [comment]
![Snipaste_2022-03-22_12-41-03](https://user-images.githubusercontent.com/47095648/159409422-cb7daae2-cd1f-4470-9418-a241ff321be1.png)

I tried this but got `The total time spanned by 'from' and 'to' must not exceed 1 year`.

**Comment by lowlighter** [comment]
Yeah, but it's possible to iterate over each year since registration date to solve this 👍
